<?php $error=flash('msg-post'); ?>
<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>ایجاد مقاله</title>
<?php require BASE_PATH.'/them/app/layout/heading.php'; ?><link rel="stylesheet" href="<?= assets('public/src/css/user-panel.css') ?>"></head><body class="user-panel-page">
<?php require BASE_PATH.'/them/app/layout/header.php'; ?><main id="main-content" class="user-panel-shell"><div class="site-container">
<div class="user-panel-head"><div><h1>مقاله جدید</h1><p>عنوان واضح، تصویر مناسب و محتوای خوانا به تجربه بهتر مخاطب کمک می‌کند.</p></div><a class="btn-site btn-site--light" href="<?= assets('user/post/1') ?>">بازگشت به مقالات</a></div>
<div class="user-panel-grid"><nav class="user-panel-nav"><div class="user-panel-nav__user"><strong><?= htmlspecialchars((string)getByUser('name'),ENT_QUOTES,'UTF-8') ?></strong></div><a href="<?= assets('panelcp') ?>">حساب</a><a class="is-active" href="<?= assets('user/post/1') ?>">مقالات من</a><a href="<?= assets('user/brand/1') ?>">محتوای برند</a></nav>
<section class="user-panel-card"><h2>اطلاعات مقاله</h2><p class="user-panel-card__lead">فیلدهای اصلی را کامل کنید و سپس برای بررسی ارسال کنید.</p><?php if($error!==''): ?><div class="user-alert user-alert--danger"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></div><?php endif; ?>
<form action="<?= assets('user/post/created') ?>" method="post" enctype="multipart/form-data"><div class="user-form-grid">
<div class="user-form-group user-form-group--full"><label class="user-form-label">تصویر شاخص</label><input class="user-input" style="padding-top:10px" type="file" name="img" accept="image/*"></div>
<div class="user-form-group user-form-group--full"><label class="user-form-label">عنوان</label><input class="user-input" required name="title" placeholder="عنوان مقاله"></div>
<div class="user-form-group user-form-group--full"><label class="user-form-label">چکیده</label><input class="user-input" name="description" placeholder="خلاصه کوتاه و دقیق"></div>
<div class="user-form-group user-form-group--full editor-wrap"><label class="user-form-label">محتوا</label><textarea class="user-textarea" required name="content" id="editor1"></textarea></div>
<div class="user-form-group"><label class="user-form-label">کلمات مرتبط</label><input class="user-input" name="tags" placeholder="مثال: تعمیرات، یخچال"></div>
<div class="user-form-group"><label class="user-form-label">دسته‌بندی</label><select class="user-select" name="post_id"><?php foreach($menus as $m): ?><option value="<?= (int)$m['id'] ?>"><?= htmlspecialchars($m['title'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div>
</div><div style="margin-top:22px"><button class="btn-site btn-site--primary" type="submit">ارسال برای بررسی</button></div></form></section></div></div></main>
<?php require BASE_PATH.'/them/app/layout/footer.php'; ?><script src="<?= assets('them/admin/plugins/ckeditor/ckeditor.js') ?>"></script><script>if(window.CKEDITOR){CKEDITOR.replace('editor1');}</script><?php require BASE_PATH.'/them/app/layout/js.php'; ?></body></html>