<?php $error=flash('msg-post'); ?>
<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>ایجاد محتوای برند</title>
<?php require BASE_PATH.'/them/app/layout/heading.php'; ?><link rel="stylesheet" href="<?= assets('public/src/css/user-panel.css') ?>"></head><body class="user-panel-page">
<?php require BASE_PATH.'/them/app/layout/header.php'; ?><main id="main-content" class="user-panel-shell"><div class="site-container">
<div class="user-panel-head"><div><h1>محتوای برند جدید</h1><p>اطلاعات دقیق و خوانا وارد کنید تا بررسی محتوا سریع‌تر انجام شود.</p></div><a class="btn-site btn-site--light" href="<?= assets('user/brand/1') ?>">بازگشت</a></div>
<div class="user-panel-grid"><nav class="user-panel-nav"><div class="user-panel-nav__user"><strong><?= htmlspecialchars((string)getByUser('name'),ENT_QUOTES,'UTF-8') ?></strong></div><a href="<?= assets('panelcp') ?>">حساب</a><a href="<?= assets('user/post/1') ?>">مقالات من</a><a class="is-active" href="<?= assets('user/brand/1') ?>">محتوای برند</a></nav>
<section class="user-panel-card"><?php if($error!==''): ?><div class="user-alert user-alert--danger"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></div><?php endif; ?>
<form action="<?= assets('user/brand/created') ?>" method="post" enctype="multipart/form-data"><div class="user-form-grid">
<div class="user-form-group user-form-group--full"><label class="user-form-label">تصویر شاخص</label><input class="user-input" style="padding-top:10px" type="file" name="img" accept="image/*" required></div>
<div class="user-form-group user-form-group--full"><label class="user-form-label">عنوان</label><input class="user-input" required name="title"></div>
<div class="user-form-group"><label class="user-form-label">آدرس انگلیسی (slug)</label><input class="user-input" required dir="ltr" name="slug" placeholder="example-brand-post"><span class="user-help">فقط حروف انگلیسی، عدد، خط تیره، نقطه یا زیرخط.</span></div>
<div class="user-form-group"><label class="user-form-label">برند</label><select class="user-select" name="brand_id"><?php foreach($item as $m): ?><option value="<?= (int)$m['id'] ?>"><?= htmlspecialchars($m['name'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div>
<div class="user-form-group user-form-group--full"><label class="user-form-label">چکیده</label><input class="user-input" name="des"></div>
<div class="user-form-group user-form-group--full editor-wrap"><label class="user-form-label">محتوا</label><textarea class="user-textarea" required name="content" id="editor1"></textarea></div>
<div class="user-form-group user-form-group--full"><label class="user-form-label">کلمات مرتبط</label><input class="user-input" name="tags"></div>
</div><div style="margin-top:22px"><button class="btn-site btn-site--primary" type="submit">ارسال برای بررسی</button></div></form></section></div></div></main>
<?php require BASE_PATH.'/them/app/layout/footer.php'; ?><script src="<?= assets('them/admin/plugins/ckeditor/ckeditor.js') ?>"></script><script>if(window.CKEDITOR){CKEDITOR.replace('editor1');}</script><?php require BASE_PATH.'/them/app/layout/js.php'; ?></body></html>