<?php
$cityName=isset($city['name'])?(string)$city['name']:'';$citySlug=isset($city['slug'])?(string)$city['slug']:'';
$services=[['slug'=>'refrigerator','icon'=>'🧊','title'=>'تعمیر یخچال','desc'=>'عیب‌یابی و تعمیر انواع یخچال و ساید'],['slug'=>'washing-machine','icon'=>'🧺','title'=>'تعمیر لباسشویی','desc'=>'تعمیر تخصصی ماشین لباسشویی در محل'],['slug'=>'air-conditioner','icon'=>'❄️','title'=>'تعمیر کولر گازی','desc'=>'سرویس و تعمیر سیستم‌های سرمایشی'],['slug'=>'tv','icon'=>'📺','title'=>'تعمیر تلویزیون','desc'=>'بررسی و تعمیر انواع تلویزیون'],['slug'=>'oven','icon'=>'🔥','title'=>'تعمیر اجاق گاز','desc'=>'رفع ایراد اجاق گاز و تجهیزات پخت'],['slug'=>'dishwasher','icon'=>'🍽️','title'=>'تعمیر ظرفشویی','desc'=>'تعمیر و سرویس ماشین ظرفشویی']];
$phone=isset($dataFooter['phon'])?strip_tags((string)$dataFooter['phon']):'';$phoneHref=preg_replace('/[^\d+]/','',$phone);
?>
<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>خدمات تعمیرات در <?= htmlspecialchars($cityName,ENT_QUOTES,'UTF-8') ?> | <?= htmlspecialchars(isset($dataSeo['title'])?strip_tags($dataSeo['title']):'الو تعمیراتچی',ENT_QUOTES,'UTF-8') ?></title><meta name="description" content="خدمات تعمیرات لوازم خانگی در <?= htmlspecialchars($cityName,ENT_QUOTES,'UTF-8') ?>؛ انتخاب سرویس و دسترسی سریع به اطلاعات تعمیرات."><?php require BASE_PATH.'/them/app/layout/heading.php'; ?></head><body>
<?php require BASE_PATH.'/them/app/layout/header.php'; ?><main id="main-content"><section class="page-hero"><div class="site-container"><div class="breadcrumbs"><a href="<?= assets('/') ?>">خانه</a> / <a href="<?= assets('cities') ?>">شهرها</a> / <?= htmlspecialchars($cityName,ENT_QUOTES,'UTF-8') ?></div><span class="site-eyebrow">خدمات در محل</span><h1>تعمیرات لوازم خانگی در <?= htmlspecialchars($cityName,ENT_QUOTES,'UTF-8') ?></h1><p>نوع دستگاه را انتخاب کنید تا جزئیات سرویس، نکات مهم و راه ارتباطی مناسب را ببینید.</p></div></section>
<section class="site-section"><div class="site-container"><div class="service-grid"><?php foreach($services as $service): ?><a class="service-card" href="<?= assets($service['slug'].'-repair-in-'.$citySlug) ?>"><div class="service-card__icon"><?= $service['icon'] ?></div><h3><?= htmlspecialchars($service['title'],ENT_QUOTES,'UTF-8') ?></h3><p><?= htmlspecialchars($service['desc'],ENT_QUOTES,'UTF-8') ?> در <?= htmlspecialchars($cityName,ENT_QUOTES,'UTF-8') ?></p></a><?php endforeach; ?></div>
<?php if($phone!==''): ?><div class="cta-panel" style="margin-top:34px"><div><h2>برای انتخاب سرویس مطمئن نیستید؟</h2><p>برای راهنمایی اولیه با پشتیبانی تماس بگیرید.</p></div><div class="cta-panel__actions"><a class="btn-site btn-site--accent" href="tel:<?= htmlspecialchars($phoneHref,ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars($phone,ENT_QUOTES,'UTF-8') ?></a></div></div><?php endif; ?></div></section></main>
<?php require BASE_PATH.'/them/app/layout/footer.php'; ?><?php require BASE_PATH.'/them/app/layout/js.php'; ?></body></html>